# Generated by Django 3.0.6 on 2020-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('room_number', models.CharField(choices=[('nab0101', 'NAB 0101'), ('nab0103', 'NAB 0103'), ('nab0104', 'NAB 0104'), ('nab0105', 'NAB 0105'), ('nab0106', 'NAB 0106'), ('nab0109', 'NAB 0109'), ('nab0111', 'NAB 0111'), ('nab0113', 'NAB 0113'), ('nab0117', 'NAB 0117'), ('nab3104', 'NAB 3104'), ('studn3326', 'STUDN 3326')], default='nab0101', max_length=10)),
                ('date_for_lab', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
