# Generated by Django 3.0.6 on 2020-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200529_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='my_id',
            field=models.AutoField( editable=False, primary_key=True, serialize=False),
        ),
    ]
