# Generated by Django 3.0.6 on 2020-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20200531_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='my_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
